name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gofmt -d .
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2.3.0
        with:
          version: v1.29