name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linter
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          version: v1.29
          skip-go-installation: true